In [12]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [13]:
tickers = pd.read_csv(r"C:\Users\naiti\Downloads\ind_nifty50list.csv")

In [14]:
tickers=tickers.Symbol.to_list()
for i in range(len(tickers)):
    tickers[i] = tickers[i]+'.NS'

In [15]:
def RSIcalc(asset):
    df = yf.download(asset,start='2020-01-01')
    df['MA200'] = df['Adj Close'].rolling(window=200).mean()
    df['price change'] = df['Adj Close'].pct_change()
    df['Upmove'] = df['price change'].apply(lambda x:x if x>0 else 0)
    df['Downmove'] = df['price change'].apply(lambda x: abs(x) if x<0 else 0)
    df['avg Up'] = df['Upmove'].ewm(span=19).mean()
    df['avg Down'] = df['Downmove'].ewm(span=19).mean()
    df.dropna(inplace=True)
    df['RS'] = df['avg Up']/df['avg Down']
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df['RSI'] = df['RS'].apply(lambda x:100-(100/(x+1)))
    df.loc[(df['Adj Close']>df['MA200']) & (df['RSI']<30),'Buy']='Yes'
    df.loc[(df['Adj Close']<df['MA200']) | (df['RSI']>30),'Buy']='No'
    df.dropna(inplace=True)
    return df

In [16]:
def getSignals(df):
    Buying_dates = []
    Selling_dates = []
    for i in range(len(df) -11):
        if "Yes" in df['Buy'].iloc[i]:
            Buying_dates.append(df.iloc[i+1].name)
            for j in range(10):
                if df['RSI'].iloc[i+j]>40:
                    Selling_dates.append(df.iloc[i+j+1].name)
                    break
                elif j == 9:
                    Selling_dates.append(df.iloc[i+j+1].name)
    return Buying_dates,Selling_dates

In [17]:
matsignals = []
matprofits = []

for i in range(len(tickers)):
    frame=RSIcalc(tickers[i])
    buy,sell = getSignals(frame)
    Profits = (frame.loc[sell].Open.values - frame.loc[buy].Open.values)/frame.loc[buy].Open.values
    matsignals.append(buy)
    matprofits.append(Profits)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%********

In [18]:
matprofits

[array([0.0443662 , 0.01547988]),
 array([ 0.08345534,  0.15049749, -0.01976285,  0.0359453 ]),
 array([ 0.02192496,  0.02967147,  0.05769514,  0.0209205 ,  0.02521008,
        -0.0184182 ,  0.00110497,  0.02604757,  0.02326632,  0.04233778]),
 array([0.04504132, 0.02972313, 0.04219892, 0.05639098, 0.0373913 ,
        0.04302521, 0.05186441, 0.06338135, 0.02436288, 0.03380647,
        0.02060442, 0.02389778, 0.02063696]),
 array([0.05199819, 0.03126525, 0.03566434]),
 array([ 0.04904311, -0.00330776,  0.0030137 ,  0.01750973,  0.02477891,
        -0.01489233, -0.0111025 , -0.00571132, -0.00519481, -0.0010433 ,
         0.00057473,  0.01430085,  0.02113802, -0.02355813, -0.03772782,
        -0.02864583, -0.08796895, -0.06236842, -0.0577027 , -0.05341044,
        -0.02421703]),
 array([ 0.04258041,  0.0189632 ,  0.01273287,  0.02285714,  0.05807596,
         0.05115942,  0.04194054, -0.00248997]),
 array([0.0640476 , 0.03490516, 0.04452955, 0.00309598, 0.01688533,
        0.07430624, 0.0

In [19]:
wins = [i for i in Profits if i>0]
len(wins)/len(Profits)

0.14285714285714285

In [22]:
ctr=0
x=0
for i in matprofits:
    ctr+=1
    add=0
    for j in i:
        add+=j
    x+=add*10000/len(i)
    print(f"{ctr}:{add*5000/len(i)}")

1:149.61518336022326
2:312.66911602631615
3:114.88029673087946
4:189.35581922888045
5:198.21296043635672
6:-68.21245391461218
7:153.63723249537924
8:258.87515545979005
9:90.81544018726176
10:87.47832062849382
11:-12.833975641580308
12:137.7552805877194
13:185.03010206945405
14:183.71427792199515
15:120.68149510525315
16:92.46084740783041
17:178.16171810402398
18:126.43773784850553
19:87.04641662244678
20:-125.0
21:-54.42238882787952
22:-487.76749946151915
23:-16.068133169506233
24:217.2079766061192
25:178.35099618691316
26:37.230082470177194
27:189.6764352679661
28:64.82452492947554
29:150.02559190820634
30:118.48690951838294
31:112.77536054372425
32:167.4864546698525
33:91.50134445074667
34:143.25383428908063
35:70.35870853112034
36:210.86810890550638
37:5.887287142161646
38:167.9579209307992
39:96.9420100117125
40:67.0580739764007
41:157.4995175048482
42:86.2747437689086
43:73.98352514363756
44:7.056555318398824
45:-42.93779695601358
46:-63.89029398461481
47:216.98456395547424
48:-7.

In [24]:
x/500000

0.0168141591305235